import { app, BrowserWindow, Tray, Menu, ipcMain, shell, nativeImage, screen } from 'electron';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { loadConfig, saveConfig, normalizeConfig, DEFAULT_CONFIG, WidgetConfig } from './core/config';
import { UsageResult } from './core/provider';
import { loadRegistry, providerInfos, Registry } from './core/registry';

// Gauge template icon: generated by scripts/gen-tray-icon.js into scripts/tray-icon.png; loaded from file at runtime (avoids base64 transcription errors)

const WIDTH = 280;
const HEIGHT = 380;

let win: BrowserWindow | null = null;
let tray: Tray | null = null;
let config: WidgetConfig = loadConfig(path.join(app.getPath('userData'), 'config.json'));
let usage: (UsageResult & { alias: string })[] = [];
let updating = false;
let pollTimer: NodeJS.Timeout | null = null;
let registry: Registry = { defs: [], errors: [] };

function configPath(): string { return path.join(app.getPath('userData'), 'config.json'); }
function pluginsDir(): string { return path.join(app.getPath('userData'), 'providers'); }
function windowStatePath(): string { return path.join(app.getPath('userData'), 'window-state.json'); }

function statePayload() {
  return { config, usage, updating, providers: providerInfos(registry), providerErrors: registry.errors };
}

function broadcast() {
  if (win && !win.isDestroyed()) win.webContents.send('usage-update', statePayload());
}

async function refreshAll() {
  if (updating) return;
  updating = true;
  broadcast();
  const results = await Promise.allSettled(
    config.accounts.map(async (a) => {
      const def = registry.defs.find((d) => d.id === a.provider);
      if (!def) {
        return { alias: a.alias, ok: false, tiers: [], error: `Unknown provider "${a.provider}"`, queriedAt: Date.now() } as UsageResult & { alias: string };
      }
      const r = await def.query(a.credentials);
      return { alias: a.alias, ...r };
    }),
  );
  usage = results.map((r, i) =>
    r.status === 'fulfilled'
      ? r.value
      : { alias: config.accounts[i]?.alias ?? `#${i}`, ok: false, tiers: [], error: String(r.reason), queriedAt: Date.now() },
  );
  updating = false;
  broadcast();
}

function schedulePoll() {
  if (pollTimer) clearInterval(pollTimer);
  if (config.refreshIntervalSec > 0) {
    pollTimer = setInterval(() => { void refreshAll(); }, config.refreshIntervalSec * 1000);
  }
}

function loadWindowBounds(): { x: number; y: number } {
  try {
    const s = JSON.parse(fs.readFileSync(windowStatePath(), 'utf8'));
    if (typeof s.x === 'number' && typeof s.y === 'number') {
      // Keep the window inside a visible display (guards against unplugged external monitors)
      const visible = screen.getAllDisplays().some((d) => {
        const wa = d.workArea;
        return s.x >= wa.x && s.x < wa.x + wa.width && s.y >= wa.y && s.y < wa.y + wa.height;
      });
      if (visible) return { x: s.x, y: s.y };
    }
  } catch { /* fall back to default position */ }
  const wa = screen.getPrimaryDisplay().workArea;
  return { x: wa.x + wa.width - WIDTH - 24, y: wa.y + 72 };
}

function createWindow() {
  const { x, y } = loadWindowBounds();
  win = new BrowserWindow({
    x, y, width: WIDTH, height: HEIGHT,
    frame: false, transparent: true, alwaysOnTop: true, resizable: false,
    skipTaskbar: true, hasShadow: false,
    webPreferences: { preload: path.join(__dirname, 'preload.js'), backgroundThrottling: false },
  });
  // Visible on all desktops/fullscreen spaces, like a sticky note
  win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  win.webContents.on('did-finish-load', () => {
    if (isSmoke) {
      console.log('SMOKE_OK: window loaded');
      setTimeout(() => app.quit(), 500);
    }
  });
  win.webContents.on('console-message', (_e: Electron.Event, level: number, message: string) => {
    console.log(`[renderer:${level}] ${message}`);
  });
  void win.loadFile(path.join(__dirname, '../src/renderer/index.html'));
  let lastSave = 0;
  win.on('move', () => {
    const now = Date.now();
    if (now - lastSave < 300 || !win) return;
    lastSave = now;
    try {
      const [wx, wy] = win.getPosition();
      fs.mkdirSync(path.dirname(windowStatePath()), { recursive: true });
      fs.writeFileSync(windowStatePath(), JSON.stringify({ x: wx, y: wy }));
    } catch { /* ignore */ }
  });
  win.on('closed', () => { win = null; });
}

// Tray menu labels per UI locale (undefined locale = follow the system language)
const TRAY_LABELS: Record<'zh' | 'en', Record<string, string>> = {
  zh: { settings: '设置…', refresh: '立即刷新', hide: '隐藏', quit: '退出' },
  en: { settings: 'Settings…', refresh: 'Refresh Now', hide: 'Hide', quit: 'Quit' },
};
let trayMenu: Menu | null = null;

function buildTrayMenu(): void {
  const locale = config.locale ?? (app.getLocale().startsWith('zh') ? 'zh' : 'en');
  const L = TRAY_LABELS[locale];
  trayMenu = Menu.buildFromTemplate([
    { label: L.settings, click: () => { if (win) { win.show(); win.webContents.send('open-settings'); } } },
    { label: L.refresh, click: () => void refreshAll() },
    { type: 'separator' },
    { label: L.hide, click: () => { win?.hide(); } },
    { label: L.quit, click: () => app.quit() },
  ]);
}

function createTray() {
  const icon = nativeImage.createFromPath(path.join(__dirname, '../scripts/tray-icon.png'));
  icon.setTemplateImage(true); // auto-inverts with the macOS menu bar appearance
  if (isSmoke) console.log('TRAY_ICON size=', icon.getSize().width, 'empty=', icon.isEmpty());
  tray = new Tray(icon);
  tray.setToolTip('TokenGauge');
  // Left click: always show the window; right click: open the menu (avoid setContextMenu so left click does not open it too)
  tray.on('click', () => { if (win) { win.show(); win.focus(); } });
  buildTrayMenu();
  tray.on('right-click', () => trayMenu && tray?.popUpContextMenu(trayMenu));
}

function registerIpc() {
  ipcMain.handle('get-state', () => statePayload());
  ipcMain.handle('get-config-path', () => configPath());
  ipcMain.handle('refresh', async () => { await refreshAll(); return statePayload(); });
  ipcMain.handle('save-config', (_e, cfg: unknown) => {
    config = normalizeConfig(cfg);
    saveConfig(configPath(), config);
    buildTrayMenu(); // menu labels follow the saved locale
    schedulePoll();
    void refreshAll();
    return statePayload();
  });
  ipcMain.handle('delete-config', () => {
    config = { ...DEFAULT_CONFIG };
    saveConfig(configPath(), config);
    usage = [];
    schedulePoll();
    broadcast();
    return statePayload();
  });
  ipcMain.handle('show-config-folder', () => { shell.showItemInFolder(configPath()); });
  ipcMain.handle('open-plugins-folder', () => { void shell.openPath(pluginsDir()); });
  ipcMain.handle('quit', () => app.quit());
}

// --smoke: exit right after boot; verifies the app can start (no network requests without accounts)
const isSmoke = process.argv.includes('--smoke');

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
} else {
  app.on('second-instance', () => { if (win) { win.show(); win.focus(); } });
  app.whenReady().then(() => {
    if (process.platform === 'darwin') app.setActivationPolicy('accessory'); // no Dock icon, tray-only
    registry = loadRegistry(pluginsDir(), path.join(__dirname, '../providers/example.js'));
    registerIpc();
    createWindow();
    createTray();
    schedulePoll();
    void refreshAll();
  });
  // Stay in the tray after close/hide; do not quit
  app.on('window-all-closed', () => { /* keep running */ });
  app.on('before-quit', () => { if (pollTimer) clearInterval(pollTimer); });
}
